### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by mentalfl0w** [nedrysoft/qt-ribbon#2]
Hello, when I try to build the plugin, there appears some errors, which contains spelling errors.
BTW:I'm very appreciate this repo, but it seems too hard to use it for my project to the Qt noob just like me. Would you like to write a guide for us? thanks. 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/30333935/107974055-fcdb5980-6ff0-11eb-95d4-3504e22743b6.png">

**Comment by fizzyade** [comment]
> Hello, when I try to build the plugin, there appears some errors, which contains spelling errors.
> BTW:I'm very appreciate this repo, but it seems too hard to use it for my project to the Qt noob just like me. Would you like to write a guide for us? thanks.
> <img alt="image" width="929" src="https://user-images.githubusercontent.com/30333935/107974055-fcdb5980-6ff0-11eb-95d4-3504e22743b6.png">

I have fixed the compilation issues and pushed the code, I hadn't built the designer plugin in a while and I forgot that Qt doesn't like modern syntax for some things.

**Comment by mentalfl0w** [comment]
> > Hello, when I try to build the plugin, there appears some errors, which contains spelling errors.
> > BTW:I'm very appreciate this repo, but it seems too hard to use it for my project to the Qt noob just like me. Would you like to write a guide for us? thanks.
> > <img alt="image" width="929" src="https://user-images.githubusercontent.com/30333935/107974055-fcdb5980-6ff0-11eb-95d4-3504e22743b6.png">
> 
> I have fixed the compilation issues and pushed the code, I hadn't built the designer plugin in a while and I forgot that Qt doesn't like modern syntax for some things.



Great work! It build well now.
But when I try to use it in Qt designer, I find the slide bar is not showed.
I have checked the CMakeLists.txt, added the SlidePlugin file to the Plugin project, but it didn't work.
There are another tabbar problem, I can't see it in designer either.
Here is the screenshot:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/30333935/108034293-4323cd80-7070-11eb-9e2b-facbfae47f50.png">

**Comment by fizzyade** [comment]
> > > Hello, when I try to build the plugin, there appears some errors, which contains spelling errors.
> > > BTW:I'm very appreciate this repo, but it seems too hard to use it for my project to the Qt noob just like me. Would you like to write a guide for us? thanks.
> > > <img alt="image" width="929" src="https://user-images.githubusercontent.com/30333935/107974055-fcdb5980-6ff0-11eb-95d4-3504e22743b6.png">
> > 
> > 
> > I have fixed the compilation issues and pushed the code, I hadn't built the designer plugin in a while and I forgot that Qt doesn't like modern syntax for some things.
> 
> Great work! It build well now.
> But when I try to use it in Qt designer, I find the slide bar is not showed.
> I have checked the CMakeLists.txt, added the SlidePlugin file to the Plugin project, but it didn't work.
> There are another tabbar problem, I can't see it in designer either.
> Here is the screenshot:
> <img alt="image" width="256" src="https://user-images.githubusercontent.com/30333935/108034293-4323cd80-7070-11eb-9e2b-facbfae47f50.png">

I have fixed it, the slider plugin should now be visible.  The tabbar is an internal widget and not exposed, you need to add a RibbonWidget to your window and then right click on it and add a page.  You can drop groups into pages and controls into groups.

**Comment by mentalfl0w** [comment]
> > > > Hello, when I try to build the plugin, there appears some errors, which contains spelling errors.
> > > > BTW:I'm very appreciate this repo, but it seems too hard to use it for my project to the Qt noob just like me. Would you like to write a guide for us? thanks.
> > > > <img alt="image" width="929" src="https://user-images.githubusercontent.com/30333935/107974055-fcdb5980-6ff0-11eb-95d4-3504e22743b6.png">
> > > 
> > > 
> > > I have fixed the compilation issues and pushed the code, I hadn't built the designer plugin in a while and I forgot that Qt doesn't like modern syntax for some things.
> > 
> > 
> > Great work! It build well now.
> > But when I try to use it in Qt designer, I find the slide bar is not showed.
> > I have checked the CMakeLists.txt, added the SlidePlugin file to the Plugin project, but it didn't work.
> > There are another tabbar problem, I can't see it in designer either.
> > Here is the screenshot:
> > <img alt="image" width="256" src="https://user-images.githubusercontent.com/30333935/108034293-4323cd80-7070-11eb-9e2b-facbfae47f50.png">
> 
> I have fixed it, the slider plugin should now be visible. The tabbar is an internal widget and not exposed, you need to add a RibbonWidget to your window and then right click on it and add a page. You can drop groups into pages and controls into groups.


It works very well now😁.
Thanks.

**Comment by fizzyade** [comment]
> It works very well now😁.
> Thanks.

Awesome.  Thanks for reporting the issues, I need to set up some unit tests to ensure I don't break things like this again in the future.
