### ISSUE TITLE
ThemeSupport is missing

### ISSUE THREAD

**Issue by Linuxmodel** [nedrysoft/qt-ribbon#3]
#include "ThemeSupport.h"

Seems this file is missing in the repo.

**Comment by Linuxmodel** [comment]
I found ThemeSupport in dmgee project, the implementation supports ObjectC only.

**Comment by fizzyade** [comment]
I recently moved the themesupport code out into a different library as it was being used in multiple places in pingnoo, I forgot to push the library.

I've now pushed it here:

https://github.com/nedrysoft/ThemeSupport

**Comment by Linuxmodel** [comment]
Got it.
I have used that from dmgee project, and will try this separate themesupport.lib in new branch again. Thanks.
