### ISSUE TITLE
ThemeSupport.h file not find error

### ISSUE THREAD

**Issue by mentalfl0w** [nedrysoft/qt-ribbon#4]
While building it shows errors like below:
**
<img width="890" alt="image" src="https://user-images.githubusercontent.com/30333935/115807396-2367a780-a41b-11eb-813b-353e76c1c415.png">
**
By the way, is it possible to add a fold function for tabbar?😁

**Comment by fizzyade** [comment]
You need to download the theme support library as well.  

Https://github.com/nedrysoft/themesupport

I will add instructions tomorrow, I moved themesupport out of the ribbon bar library recently to remove code duplication from pingnoo, which is why this is happening.

**Comment by fizzyade** [comment]
@Dracanrage what is folding?  The ribbon is a basic implementation, I haven't got around to implementing some of the behaviours yet.

**Comment by mentalfl0w** [comment]
> You need to download the theme support library as well.
> 
> [Https://github.com/nedrysoft/themesupport](Https://github.com/nedrysoft/themesupport)
> 
> I will add instructions tomorrow, I moved themesupport out of the ribbon bar library recently to remove code duplication from pingnoo, which is why this is happening.

OK! Now it builds no errors after I add it, thanks.

**Comment by mentalfl0w** [comment]
> @Dracanrage what is folding? The ribbon is a basic implementation, I haven't got around to implementing some of the behaviours yet.

Like Microsoft Word:
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/30333935/115812468-04214800-a424-11eb-8bcc-245980778a29.png">

**Comment by mentalfl0w** [comment]
> @Dracanrage what is folding? The ribbon is a basic implementation, I haven't got around to implementing some of the behaviours yet.

By the way, could this line's color be changed by custom?🤔
<img width="356" alt="image" src="https://user-images.githubusercontent.com/30333935/115812701-5e220d80-a424-11eb-8183-84bdc25b7e9b.png">

**Comment by fizzyade** [comment]
Yes, although not dynamically currently, you'd need to edit the appropriate colour in RibbonWidget.h

There are 2 colours per item, one for light mode and another for dark.

**Comment by mentalfl0w** [comment]
> Yes, although not dynamically currently, you'd need to edit the appropriate colour in RibbonWidget.h
> 
> There are 2 colours per item, one for light mode and another for dark.

OK~😊
